# SovereignSky English Language Configuration

languageCode = "en"
languageName = "English"
weight = 1
title = "SovereignSky"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Practical resources for Nordic digital sovereignty"
  copyright = "Published by [Helpers.no](https://helpers.no)"

[params.author]
  name = "Helpers.no"
  headline = "Navigate Digital Sovereignty"
  bio = "Practical resources for Nordic digital sovereignty"
