# Main Menu - displayed in the header
# This overrides the theme's default menu

[[main]]
  name = "Databases"
  weight = 20

[[main]]
  name = "Datacenters"
  parent = "Databases"
  pageRef = "datacenters"
  weight = 21

[[main]]
  name = "Countries"
  parent = "Databases"
  pageRef = "countries"
  weight = 22

[[main]]
  name = "Laws"
  parent = "Databases"
  pageRef = "laws"
  weight = 23

[[main]]
  name = "Networks"
  parent = "Databases"
  pageRef = "networks"
  weight = 24

[[main]]
  name = "Software"
  parent = "Databases"
  pageRef = "software"
  weight = 25

[[main]]
  name = "Learn"
  weight = 30

[[main]]
  name = "Blog"
  parent = "Learn"
  pageRef = "blog"
  weight = 31

[[main]]
  name = "Publications"
  parent = "Learn"
  pageRef = "publications"
  weight = 32

[[main]]
  name = "Personas"
  parent = "Learn"
  pageRef = "personas"
  weight = 33

[[main]]
  name = "Engage"
  weight = 40

[[main]]
  name = "Events"
  parent = "Engage"
  pageRef = "events"
  weight = 41

[[main]]
  name = "Topics"
  parent = "Learn"
  pageRef = "topics"
  weight = 34

[[main]]
  name = "Totalforsvarsåret"
  pageRef = "totalforsvarsaret"
  weight = 50

[[main]]
  name = "SovereignSky"
  pageRef = "sovereignsky"
  weight = 55

[[main]]
  name = "About"
  pageRef = "about"
  weight = 60

# Footer Menu - displayed in the footer
[[footer]]
  name = "NDSI survey"
  pageRef = "ndsi/survey"
  weight = 10

[[footer]]
  name = "Software"
  pageRef = "software"
  weight = 20

[[footer]]
  name = "Datacenters"
  pageRef = "datacenters"
  weight = 30

[[footer]]
  name = "Countries"
  pageRef = "countries"
  weight = 35

[[footer]]
  name = "Laws"
  pageRef = "laws"
  weight = 50

[[footer]]
  name = "Totalforsvarsåret 2026"
  pageRef = "totalforsvarsaret"
  weight = 60

[[footer]]
  name = "Blog"
  pageRef = "blog"
  weight = 70

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 80

[[footer]]
  name = "GitHub"
  url = "https://github.com/terchris/sovereignsky-site"
  weight = 90

[[footer]]
  name = "helpers.no"
  url = "https://helpers.no"
  weight = 100
